In [1]:
import torch

# Define two tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Element-wise multiplication using torch.einsum
result = torch.einsum('i,i->i', x, y)

print("Result of element-wise multiplication:")
print(result)


Result of element-wise multiplication:
tensor([ 4, 10, 18])


In [2]:
import torch

# Define two tensors
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

# Dot product using torch.einsum
result = torch.einsum('i,i->', x, y)

print("Result of dot product:")
print(result)


Result of dot product:
tensor(32)


In [3]:
import torch

# Define a tensor
x = torch.tensor([[1, 2], [3, 4]])

# Transpose using torch.einsum
result = torch.einsum('ij->ji', x)

print("Result of transpose:")
print(result)


Result of transpose:
tensor([[1, 3],
        [2, 4]])


In [5]:
import torch

# Define three tensors of shape (2, 2, 2)
x = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
y = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

print(f'shape of x: {x.shape}')
print(f'shape of y: {y.shape}')

# Batch matrix multiplication using torch.einsum
result = torch.einsum('bij,bjk->bik', x, y)

print("Result of batch matrix multiplication:")
print(result)


shape of x: torch.Size([2, 2, 2])
shape of y: torch.Size([2, 2, 2])
Result of batch matrix multiplication:
tensor([[[ 31,  34],
         [ 71,  78]],

        [[155, 166],
         [211, 226]]])
